export default {
  login: 'yuyunfrancis',
  id: 47271123,
  node_id: 'MDQ6VXNlcjQ3MjcxMTIz',
  avatar_url: 'https://avatars.githubusercontent.com/u/47271123?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/yuyunfrancis',
  html_url: 'https://github.com/yuyunfrancis',
  followers_url: 'https://api.github.com/users/yuyunfrancis/followers',
  following_url:
    'https://api.github.com/users/yuyunfrancis/following{/other_user}',
  gists_url: 'https://api.github.com/users/yuyunfrancis/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/yuyunfrancis/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/yuyunfrancis/subscriptions',
  organizations_url: 'https://api.github.com/users/yuyunfrancis/orgs',
  repos_url: 'https://api.github.com/users/yuyunfrancis/repos',
  events_url: 'https://api.github.com/users/yuyunfrancis/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/yuyunfrancis/received_events',
  type: 'User',
  site_admin: false,
  name: 'Yuyun Francis',
  company: 'Falcon Innovations',
  blog: 'https://yuyunfrancis.github.io/francis-portfolio.github.io/',
  location: 'Douala Cameroon',
  email: null,
  hireable: null,
  bio: '’m a web developer with extensive knowledge and years of experience, working in web technologies and Ui / Ux design, delivering quality work.',
  twitter_username: 'yuyunfrancis',
  public_repos: 39,
  public_gists: 0,
  followers: 7,
  following: 18,
  created_at: '2019-02-02T10:17:05Z',
  updated_at: '2022-02-08T21:44:07Z',
};
