export default [
  {
    login: 'WendahNyiawung',
    id: 42493128,
    node_id: 'MDQ6VXNlcjQyNDkzMTI4',
    avatar_url: 'https://avatars.githubusercontent.com/u/42493128?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/WendahNyiawung',
    html_url: 'https://github.com/WendahNyiawung',
    followers_url: 'https://api.github.com/users/WendahNyiawung/followers',
    following_url:
      'https://api.github.com/users/WendahNyiawung/following{/other_user}',
    gists_url: 'https://api.github.com/users/WendahNyiawung/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/WendahNyiawung/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/WendahNyiawung/subscriptions',
    organizations_url: 'https://api.github.com/users/WendahNyiawung/orgs',
    repos_url: 'https://api.github.com/users/WendahNyiawung/repos',
    events_url: 'https://api.github.com/users/WendahNyiawung/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/WendahNyiawung/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Tchouanga12',
    id: 53564338,
    node_id: 'MDQ6VXNlcjUzNTY0MzM4',
    avatar_url: 'https://avatars.githubusercontent.com/u/53564338?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Tchouanga12',
    html_url: 'https://github.com/Tchouanga12',
    followers_url: 'https://api.github.com/users/Tchouanga12/followers',
    following_url:
      'https://api.github.com/users/Tchouanga12/following{/other_user}',
    gists_url: 'https://api.github.com/users/Tchouanga12/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Tchouanga12/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Tchouanga12/subscriptions',
    organizations_url: 'https://api.github.com/users/Tchouanga12/orgs',
    repos_url: 'https://api.github.com/users/Tchouanga12/repos',
    events_url: 'https://api.github.com/users/Tchouanga12/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Tchouanga12/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'DassoAhmed',
    id: 65762595,
    node_id: 'MDQ6VXNlcjY1NzYyNTk1',
    avatar_url: 'https://avatars.githubusercontent.com/u/65762595?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/DassoAhmed',
    html_url: 'https://github.com/DassoAhmed',
    followers_url: 'https://api.github.com/users/DassoAhmed/followers',
    following_url:
      'https://api.github.com/users/DassoAhmed/following{/other_user}',
    gists_url: 'https://api.github.com/users/DassoAhmed/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/DassoAhmed/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/DassoAhmed/subscriptions',
    organizations_url: 'https://api.github.com/users/DassoAhmed/orgs',
    repos_url: 'https://api.github.com/users/DassoAhmed/repos',
    events_url: 'https://api.github.com/users/DassoAhmed/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/DassoAhmed/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Nwoteh',
    id: 81310229,
    node_id: 'MDQ6VXNlcjgxMzEwMjI5',
    avatar_url: 'https://avatars.githubusercontent.com/u/81310229?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Nwoteh',
    html_url: 'https://github.com/Nwoteh',
    followers_url: 'https://api.github.com/users/Nwoteh/followers',
    following_url: 'https://api.github.com/users/Nwoteh/following{/other_user}',
    gists_url: 'https://api.github.com/users/Nwoteh/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Nwoteh/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Nwoteh/subscriptions',
    organizations_url: 'https://api.github.com/users/Nwoteh/orgs',
    repos_url: 'https://api.github.com/users/Nwoteh/repos',
    events_url: 'https://api.github.com/users/Nwoteh/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Nwoteh/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'sstPiero',
    id: 92342783,
    node_id: 'U_kgDOBYEJ_w',
    avatar_url: 'https://avatars.githubusercontent.com/u/92342783?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/sstPiero',
    html_url: 'https://github.com/sstPiero',
    followers_url: 'https://api.github.com/users/sstPiero/followers',
    following_url:
      'https://api.github.com/users/sstPiero/following{/other_user}',
    gists_url: 'https://api.github.com/users/sstPiero/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/sstPiero/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/sstPiero/subscriptions',
    organizations_url: 'https://api.github.com/users/sstPiero/orgs',
    repos_url: 'https://api.github.com/users/sstPiero/repos',
    events_url: 'https://api.github.com/users/sstPiero/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/sstPiero/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'AtemnkengNJeff',
    id: 92603127,
    node_id: 'U_kgDOBYUC9w',
    avatar_url: 'https://avatars.githubusercontent.com/u/92603127?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/AtemnkengNJeff',
    html_url: 'https://github.com/AtemnkengNJeff',
    followers_url: 'https://api.github.com/users/AtemnkengNJeff/followers',
    following_url:
      'https://api.github.com/users/AtemnkengNJeff/following{/other_user}',
    gists_url: 'https://api.github.com/users/AtemnkengNJeff/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/AtemnkengNJeff/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/AtemnkengNJeff/subscriptions',
    organizations_url: 'https://api.github.com/users/AtemnkengNJeff/orgs',
    repos_url: 'https://api.github.com/users/AtemnkengNJeff/repos',
    events_url: 'https://api.github.com/users/AtemnkengNJeff/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/AtemnkengNJeff/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'TheAttackJoke',
    id: 92604536,
    node_id: 'U_kgDOBYUIeA',
    avatar_url: 'https://avatars.githubusercontent.com/u/92604536?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/TheAttackJoke',
    html_url: 'https://github.com/TheAttackJoke',
    followers_url: 'https://api.github.com/users/TheAttackJoke/followers',
    following_url:
      'https://api.github.com/users/TheAttackJoke/following{/other_user}',
    gists_url: 'https://api.github.com/users/TheAttackJoke/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/TheAttackJoke/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/TheAttackJoke/subscriptions',
    organizations_url: 'https://api.github.com/users/TheAttackJoke/orgs',
    repos_url: 'https://api.github.com/users/TheAttackJoke/repos',
    events_url: 'https://api.github.com/users/TheAttackJoke/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/TheAttackJoke/received_events',
    type: 'User',
    site_admin: false,
  },
];
